version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db_env.yaml
    expose:
      - 5432

  # just for the test assumption
  products-run-migrations:
    container_name: migration
    build: .
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure  # We don't wait until db waking up. We try few times.
    command: python ./fixture.py

  counter:
    container_name: counter
    build:
      context: .
      args:
        YOUR_ENV: production
    restart: always
    ports:
      - "8072:8072"
    depends_on:
      - db
      - products-run-migrations
    env_file:
      - .env
    command: python ./duplicate_counter/duplicate_counter.py

  nginx:
    image: nginx:1.19.6-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
# Optional for some static
#      - ./static:/var/www/static
    ports:
      - "80:80"
    depends_on:
      - counter
