version: '3'

volumes:
  postgres_data:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/postgres_data'

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db_env.yaml
#    expose:
#      - 5432
    network_mode: "host"

#  counter:
#    container_name: counter
#    build: .
#    restart: always
#    ports:
#      - "8072:8072"
#    depends_on:
#      - db
#    env_file:
#      - .env
#    command: python ./duplicate_counter/duplicate_counter.py
